# Uppdaterad docker-compose.yml
version: '3.8'

services:
  db:
    # Använd den officiella MySQL 8.0-avbildningen
    image: mysql:8.0
    # Sätt miljövariabler för databasen
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: ss12000_db
    # Spara databasdata i en namngiven volym
    volumes:
      # Denna del är viktig: den monterar vårt databas-inställningsskript
      # och MySQL kommer automatiskt att köra det vid första uppstarten.
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      # Spara data även om containern tas bort
      - db_data:/var/lib/mysql
    # Definiera en hälsokontroll för att säkerställa att databasen är redo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    # Bygg avbildningen från den lokala Dockerfilen
    build: .
    # Mappa port 8000 på värden till port 8000 i containern
    ports:
      - "8000:8000"
    # Detta säkerställer att app-containern inte startar förrän 'db'-containern
    # rapporteras som frisk av sin hälsokontroll.
    depends_on:
      db:
        condition: service_healthy
    # Skicka databasanslutningssträngen som en miljövariabel
    environment:
      DATABASE_URL: mysql+mysqlconnector://root:my_root_password@db:3306/ss12000_db
    # Montera den lokala källkoden i containern för automatisk omladdning
    volumes:
      - .:/app

volumes:
  db_data:
